### ISSUE TITLE
CSS and Styling organization

### ISSUE THREAD

**Issue by ryankazokas** [ryankazokas/beerio-web#15]
There is a mix between the use of vue material as well as bootstrap. We should eventually just choose one or the other, or just go with a different styling framework.

**Comment by Obs-Dev** [comment]
I think we should just go with Bootstrap. It's better supported in the development community and we can easily implement our own design/styling. Let me know what you think.

**Comment by ryankazokas** [comment]
Good by me. The only reason i was considering the vue material was because they have the custom components like a button that are easier to use within the javascript itself but we can create those ourselves. I will close this and open a new issue to remove the vue material and switch over to bootstrap.
