### ISSUE TITLE
Issue with dependency version of passport

### ISSUE THREAD

**Issue by ryankazokas** [ryankazokas/BeerIO-web#8]
Passport has a transitive depencency to the oauth league server which causes issues in the newest fix.

**Comment by Obs-Dev** [comment]
Can't seem to replicate this issue. I did receive a key length error after first installing passport. Running `php artisan key:generate` fixed this issue for me. *Currently running Laravel Framwork 5.4.28.*

**Comment by ryankazokas** [comment]
Ah, i remember you saying you were on windows. I'm thinking it might only be a linux issue.

**Comment by Obs-Dev** [comment]
I'll see if I can replicate it on my Linux machine later this evening.

**Comment by ryankazokas** [comment]
@Obs-Dev This wasn't a start up error. This is an error when trying to make request and authenticating via passport. So any type of rest request, login being one of them. I was having issues with child routes for right now, so i just made an update to it, but if you now go to the /authlogin page and click the login button, that is actually where it is showing the exception

**Comment by ryankazokas** [comment]
It's an issue with the oauth implementation that passport uses. I was able to get past this error by changing the permissions within the docker container to 0600 and changing the user:group combo to laradock

```
sudo chmod 0600 storage/oauth*
sudo chown laradock:laradock storage/oauth*
```

**Comment by ryankazokas** [comment]
Ignore this, i've updated the permissions to the latest laravel/passport version and manuallly change the permissions. i will add this as part of the set up instructions.
